### PR TITLE
Added `keyEncodingStrategy` parameter to JSONEncodable

### PR DESCRIPTION
**Pull request by Pomanks**

### CODE REVIEW

**Comment by philprime** [comment]
Hi there! This looks promising, looking forward to merge the changes.

Can you please add more context/descriptions what exact issue you are fixing?
Your title suggests changing the `keyEncodingStrategy` but you also changed the typing of `QueryItem`.

Also some unit tests would be great

**Comment by Pomanks** [comment]
Sure! I added the option to choose the `keyEncodingStrategy` (e.g. for APIs using camelCase naming convention) as well as extended QueryItem type support for `Double`.

In the header decoding, I allowed the decoded type to be anything we want (`String`, `Int`, …) instead of only a `String`.

Also, in the PR you'll find some access modifiers moved from methods to the extension itself (to make it clearer in the extension declaration).

I'll add some tests for the `keyEncodingStrategy`. Please let me know if something is still unclear :)

**Comment by philprime** [comment]
Alright thanks for the clarification! I agree with the query item and header changes too.
Looking forward to see the test cases.

Regarding this PR:
I squash commits of PRs so that `WIP`, `Fixed merge conflicts` etc. are not in the main history.
As you have three changes in one PR they would also be squashed into a single larger commit.

As splitting this up into individual PRs would need to be done by you, I'll let you decide if you are willing to invest the additional effort, so we have three different commits in the history (very helpful for [`git-bisect`](https://git-scm.com/docs/git-bisect)) :)

**Comment by Pomanks** [comment]
I'll see what I can do then :)

**Pull request closed without merging**
